### ISSUE TITLE
需要增加多個型別支援

### ISSUE THREAD

**Issue by frankvicky** [zheyuleetw/jmonster#3]
Int 對應 INTEGER
Long 對應 BIGINT
Float 對應 REAL
Double 對應 DOUBLE PRECISION
String 對應 TEXT
Boolean 對應 BOOLEAN
LocalDate 對應 DATE
LocalTime 對應 TIME
LocalDateTime 對應 TIMESTAMP
ByteArray 對應 BYTEA
UUID 對應 UUID
Enum 對應 TEXT
List 對應 JSONB
Map 對應 JSONB
BigDecimal 對應 decimal

**Comment by zheyuleetw** [comment]
- [ x ]  Int 對應 INTEGER 


Long 對應 BIGINT
Float 對應 REAL
Double 對應 DOUBLE PRECISION
String 對應 TEXT
Boolean 對應 BOOLEAN
LocalDate 對應 DATE
LocalTime 對應 TIME
LocalDateTime 對應 TIMESTAMP
ByteArray 對應 BYTEA
UUID 對應 UUID
Enum 對應 TEXT
List 對應 JSONB
Map 對應 JSONB
BigDecimal 對應 decimal

**Comment by zheyuleetw** [comment]
:white_check_mark: Int 對應 INTEGER 
:white_check_mark: Long 對應 BIGINT
:white_check_mark: Float 對應 REAL
:white_check_mark: Double 對應 DOUBLE PRECISION
:white_check_mark: String 對應 TEXT
:white_check_mark: Boolean 對應 BOOLEAN
:white_check_mark:  LocalDate 對應 DATE
:white_check_mark:  LocalTime 對應 TIME
:white_check_mark:  LocalDateTime 對應 TIMESTAMP
:white_check_mark:  ByteArray 對應 BYTEA
:white_check_mark:  UUID 對應 UUID
:white_check_mark:  String 對應 ENUM
:white_check_mark:  List 對應 JSONB(LIST)
:white_check_mark:  Map 對應 JSONB(MAP)
:white_check_mark:  BigDecimal 對應 decimal/numeric
